<?php

/*
 * Copyright (C) 2017-2025 CRLibre <https://crlibre.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Boot up procedure
 */
function genXML_bootMeUp()
{
    // Just booting up
}

/**
 * Init function
 */
function genXML_init()
{
    $paths = [
        [
            'r' => 'gen_xml_mr',                                                    // Mensaje de aceptacion o rechazo de los documentos electronicos por parte del obligado tributario
            'action' => 'genXMLMr',
            'access' => 'users_openAccess',
            'access_params' => 'accessName',
            'params' => [
                ['key' => 'clave', 'def' => '', 'req' => true],    // d{50,50} equivale a clave en FE
                ['key' => 'codigo_actividad', 'def' => '', 'req' => true],
                ['key' => 'numero_cedula_emisor', 'def' => '', 'req' => true],    // d{12,12} equivale a emisor_num_identif en FE
                ['key' => 'fecha_emision_doc', 'def' => '', 'req' => true],    // YYYY-MM-DDThh:mm:ss-06:00 ej: 2018-05-13T15:30:00-06:00
                ['key' => 'mensaje', 'def' => '', 'req' => true],    // 1 - Aceptado, 2 - Aceptado Parcialmente, 3 - Rechazado
                ['key' => 'detalle_mensaje', 'def' => '', 'req' => false],   // s80
                ['key' => 'monto_total_impuesto', 'def' => '', 'req' => false],   // d18,5 equivale a total_impuestos en FE
                ['key' => 'total_factura', 'def' => '', 'req' => true],    // d18,5 equivale a total_comprobante en FE
                ['key' => 'numero_cedula_receptor', 'def' => '', 'req' => true],    // d{12,12} equivale a receptor_num_identif en FE
                ['key' => 'numero_consecutivo_receptor', 'def' => '', 'req' => true],     // d{20,20} numeracion consecutiva de los mensajes de confirmacion
            ],
            'file' => 'genXML.php',
        ],
        [
            'r' => 'gen_xml_fe',
            'action' => 'genXMLFe',
            'access' => 'users_openAccess',
            'access_params' => 'accessName',
            'params' => [
                ['key' => 'clave', 'def' => '', 'req' => true],
                ['key' => 'proveedor_sistemas', 'def' => '', 'req' => true],
                ['key' => 'codigo_actividad_emisor', 'def' => '', 'req' => true],
                ['key' => 'codigo_actividad_receptor', 'def' => '', 'req' => false],
                ['key' => 'consecutivo', 'def' => '', 'req' => true],
                ['key' => 'fecha_emision', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre', 'def' => '', 'req' => true],
                ['key' => 'emisor_tipo_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_num_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'emisor_provincia', 'def' => '', 'req' => true],
                ['key' => 'emisor_canton', 'def' => '', 'req' => true],
                ['key' => 'emisor_distrito', 'def' => '', 'req' => true],
                ['key' => 'emisor_barrio', 'def' => '', 'req' => false],
                ['key' => 'emisor_otras_senas', 'def' => '', 'req' => true],
                ['key' => 'emisor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_email', 'def' => '', 'req' => true],
                ['key' => 'receptor_nombre', 'def' => '', 'req' => true],
                ['key' => 'receptor_tipo_identif', 'def' => '', 'req' => true],
                ['key' => 'receptor_num_identif', 'def' => '', 'req' => true],
                ['key' => 'receptor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'receptor_provincia', 'def' => '', 'req' => false],
                ['key' => 'receptor_canton', 'def' => '', 'req' => false],
                ['key' => 'receptor_distrito', 'def' => '', 'req' => false],
                ['key' => 'receptor_barrio', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas_extranjero', 'def' => '', 'req' => false],
                ['key' => 'receptor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_email', 'def' => '', 'req' => false],
                ['key' => 'registrofiscal8707', 'def' => '', 'req' => false],
                ['key' => 'condicion_venta', 'def' => '', 'req' => true],
                ['key' => 'condicion_venta_otros', 'def' => '', 'req' => false],
                ['key' => 'plazo_credito', 'def' => '0', 'req' => false],
                ['key' => 'medios_pago', 'def' => '', 'req' => true],
                ['key' => 'cod_moneda', 'def' => '', 'req' => true],
                ['key' => 'tipo_cambio', 'def' => '', 'req' => true],
                ['key' => 'total_serv_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exentos', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exonerados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_merc_gravada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exenta', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exonerada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_no_sujeta', 'def' => '', 'req' => false],
                ['key' => 'total_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_exento', 'def' => '', 'req' => false],
                ['key' => 'total_exonerado', 'def' => '', 'req' => false],
                ['key' => 'total_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_ventas', 'def' => '', 'req' => true],
                ['key' => 'total_descuentos', 'def' => '', 'req' => false],
                ['key' => 'total_ventas_neta', 'def' => '', 'req' => true],
                ['key' => 'totalDesgloseImpuesto', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos_asumidos_fabrica', 'def' => '', 'req' => false],
                ['key' => 'totalIVADevuelto', 'def' => '0', 'req' => false],
                ['key' => 'totalOtrosCargos', 'def' => '', 'req' => false],
                ['key' => 'total_comprobante', 'def' => '', 'req' => true],
                ['key' => 'otros', 'def' => '', 'req' => false],
                ['key' => 'detalles', 'def' => '', 'req' => true],
                ['key' => 'informacion_referencia', 'def' => '', 'req' => false],
                ['key' => 'otrosCargos', 'def' => '', 'req' => false],
            ],
            'file' => 'genXML.php',
        ],
        [
            'r' => 'gen_xml_nc',
            'action' => 'genXMLNC',
            'access' => 'users_openAccess',
            'access_params' => 'accessName',
            'params' => [
                ['key' => 'clave', 'def' => '', 'req' => true],
                ['key' => 'proveedor_sistemas', 'def' => '', 'req' => true],
                ['key' => 'codigo_actividad_emisor', 'def' => '', 'req' => true],
                ['key' => 'codigo_actividad_receptor', 'def' => '', 'req' => false],
                ['key' => 'consecutivo', 'def' => '', 'req' => true],
                ['key' => 'fecha_emision', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre', 'def' => '', 'req' => true],
                ['key' => 'emisor_tipo_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_num_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'emisor_provincia', 'def' => '', 'req' => true],
                ['key' => 'emisor_canton', 'def' => '', 'req' => true],
                ['key' => 'emisor_distrito', 'def' => '', 'req' => true],
                ['key' => 'emisor_barrio', 'def' => '', 'req' => false],
                ['key' => 'emisor_otras_senas', 'def' => '', 'req' => true],
                ['key' => 'emisor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_email', 'def' => '', 'req' => true],
                ['key' => 'omitir_receptor', 'def' => 'false', 'req' => false],
                ['key' => 'receptor_nombre', 'def' => '', 'req' => false],
                ['key' => 'receptor_tipo_identif', 'def' => '', 'req' => false],
                ['key' => 'receptor_num_identif', 'def' => '', 'req' => false],
                ['key' => 'receptor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'receptor_provincia', 'def' => '', 'req' => false],
                ['key' => 'receptor_canton', 'def' => '', 'req' => false],
                ['key' => 'receptor_distrito', 'def' => '', 'req' => false],
                ['key' => 'receptor_barrio', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas_extranjero', 'def' => '', 'req' => false],
                ['key' => 'receptor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_email', 'def' => '', 'req' => false],
                ['key' => 'registrofiscal8707', 'def' => '', 'req' => false],
                ['key' => 'condicion_venta', 'def' => '', 'req' => true],
                ['key' => 'condicion_venta_otros', 'def' => '', 'req' => false],
                ['key' => 'plazo_credito', 'def' => '0', 'req' => false],
                ['key' => 'medios_pago', 'def' => '', 'req' => true],
                ['key' => 'cod_moneda', 'def' => '', 'req' => true],
                ['key' => 'tipo_cambio', 'def' => '', 'req' => true],
                ['key' => 'total_serv_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exentos', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exonerados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_merc_gravada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exenta', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exonerada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_no_sujeta', 'def' => '', 'req' => false],
                ['key' => 'total_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_exento', 'def' => '', 'req' => false],
                ['key' => 'total_exonerado', 'def' => '', 'req' => false],
                ['key' => 'total_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_ventas', 'def' => '', 'req' => true],
                ['key' => 'total_descuentos', 'def' => '', 'req' => false],
                ['key' => 'total_ventas_neta', 'def' => '', 'req' => true],
                ['key' => 'totalDesgloseImpuesto', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos_asumidos_fabrica', 'def' => '', 'req' => false],
                ['key' => 'totalIVADevuelto', 'def' => '0', 'req' => false],
                ['key' => 'totalOtrosCargos', 'def' => '', 'req' => false],
                ['key' => 'total_comprobante', 'def' => '', 'req' => true],
                ['key' => 'otros', 'def' => '', 'req' => false],
                ['key' => 'otrosType', 'def' => '', 'req' => false],
                ['key' => 'detalles', 'def' => '', 'req' => true],
                ['key' => 'informacion_referencia', 'def' => '', 'req' => true],
                ['key' => 'otrosCargos', 'def' => '', 'req' => false],
            ],
            'file' => 'genXML.php',
        ],
        [
            'r' => 'gen_xml_nd',
            'action' => 'genXMLND',
            'access' => 'users_openAccess',
            'access_params' => 'accessName',
            'params' => [
                ['key' => 'clave', 'def' => '', 'req' => true],
                ['key' => 'proveedor_sistemas', 'def' => '', 'req' => true],
                ['key' => 'codigo_actividad_emisor', 'def' => '', 'req' => true],
                ['key' => 'codigo_actividad_receptor', 'def' => '', 'req' => false],
                ['key' => 'consecutivo', 'def' => '', 'req' => true],
                ['key' => 'fecha_emision', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre', 'def' => '', 'req' => true],
                ['key' => 'emisor_tipo_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_num_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'emisor_provincia', 'def' => '', 'req' => true],
                ['key' => 'emisor_canton', 'def' => '', 'req' => true],
                ['key' => 'emisor_distrito', 'def' => '', 'req' => true],
                ['key' => 'emisor_barrio', 'def' => '', 'req' => false],
                ['key' => 'emisor_otras_senas', 'def' => '', 'req' => true],
                ['key' => 'emisor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_email', 'def' => '', 'req' => true],
                ['key' => 'omitir_receptor', 'def' => 'false', 'req' => false],
                ['key' => 'receptor_nombre', 'def' => '', 'req' => false],
                ['key' => 'receptor_tipo_identif', 'def' => '', 'req' => false],
                ['key' => 'receptor_num_identif', 'def' => '', 'req' => false],
                ['key' => 'receptor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'receptor_provincia', 'def' => '', 'req' => false],
                ['key' => 'receptor_canton', 'def' => '', 'req' => false],
                ['key' => 'receptor_distrito', 'def' => '', 'req' => false],
                ['key' => 'receptor_barrio', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas_extranjero', 'def' => '', 'req' => false],
                ['key' => 'receptor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_email', 'def' => '', 'req' => false],
                ['key' => 'registrofiscal8707', 'def' => '', 'req' => false],
                ['key' => 'condicion_venta', 'def' => '', 'req' => true],
                ['key' => 'condicion_venta_otros', 'def' => '', 'req' => false],
                ['key' => 'plazo_credito', 'def' => '0', 'req' => false],
                ['key' => 'medios_pago', 'def' => '', 'req' => true],
                ['key' => 'cod_moneda', 'def' => '', 'req' => true],
                ['key' => 'tipo_cambio', 'def' => '', 'req' => true],
                ['key' => 'total_serv_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exentos', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exonerados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_merc_gravada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exenta', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exonerada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_no_sujeta', 'def' => '', 'req' => false],
                ['key' => 'total_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_exento', 'def' => '', 'req' => false],
                ['key' => 'total_exonerado', 'def' => '', 'req' => false],
                ['key' => 'total_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_ventas', 'def' => '', 'req' => true],
                ['key' => 'total_descuentos', 'def' => '', 'req' => false],
                ['key' => 'total_ventas_neta', 'def' => '', 'req' => true],
                ['key' => 'totalDesgloseImpuesto', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos_asumidos_fabrica', 'def' => '', 'req' => false],
                ['key' => 'totalIVADevuelto', 'def' => '0', 'req' => false],
                ['key' => 'totalOtrosCargos', 'def' => '', 'req' => false],
                ['key' => 'total_comprobante', 'def' => '', 'req' => true],
                ['key' => 'otros', 'def' => '', 'req' => false],
                ['key' => 'otrosType', 'def' => '', 'req' => false],
                ['key' => 'detalles', 'def' => '', 'req' => true],
                ['key' => 'informacion_referencia', 'def' => '', 'req' => true],
                ['key' => 'otrosCargos', 'def' => '', 'req' => false],
            ],
            'file' => 'genXML.php',
        ],
        [
            'r' => 'gen_xml_te',
            'action' => 'genXMLTE',
            'access' => 'users_openAccess',
            'access_params' => 'accessName',
            'params' => [
                ['key' => 'clave', 'def' => '', 'req' => true],
                ['key' => 'proveedor_sistemas', 'def' => '', 'req' => true],
                ['key' => 'codigo_actividad_emisor', 'def' => '', 'req' => true],
                ['key' => 'consecutivo', 'def' => '', 'req' => true],
                ['key' => 'fecha_emision', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre', 'def' => '', 'req' => true],
                ['key' => 'emisor_tipo_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_num_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'emisor_provincia', 'def' => '', 'req' => true],
                ['key' => 'emisor_canton', 'def' => '', 'req' => true],
                ['key' => 'emisor_distrito', 'def' => '', 'req' => true],
                ['key' => 'emisor_barrio', 'def' => '', 'req' => false],
                ['key' => 'emisor_otras_senas', 'def' => '', 'req' => true],
                ['key' => 'emisor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_email', 'def' => '', 'req' => true],
                ['key' => 'omitir_receptor', 'def' => 'false', 'req' => false],
                ['key' => 'receptor_nombre', 'def' => '', 'req' => false],
                ['key' => 'receptor_tipo_identif', 'def' => '', 'req' => false],
                ['key' => 'receptor_num_identif', 'def' => '', 'req' => false],
                ['key' => 'receptor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'receptor_provincia', 'def' => '', 'req' => false],
                ['key' => 'receptor_canton', 'def' => '', 'req' => false],
                ['key' => 'receptor_distrito', 'def' => '', 'req' => false],
                ['key' => 'receptor_barrio', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas_extranjero', 'def' => '', 'req' => false],
                ['key' => 'receptor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_email', 'def' => '', 'req' => false],
                ['key' => 'registrofiscal8707', 'def' => '', 'req' => false],
                ['key' => 'condicion_venta', 'def' => '', 'req' => true],
                ['key' => 'condicion_venta_otros', 'def' => '', 'req' => false],
                ['key' => 'plazo_credito', 'def' => '0', 'req' => false],
                ['key' => 'medios_pago', 'def' => '', 'req' => true],
                ['key' => 'cod_moneda', 'def' => '', 'req' => true],
                ['key' => 'tipo_cambio', 'def' => '', 'req' => true],
                ['key' => 'total_serv_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exentos', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exonerados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_merc_gravada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exenta', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exonerada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_no_sujeta', 'def' => '', 'req' => false],
                ['key' => 'total_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_exento', 'def' => '', 'req' => false],
                ['key' => 'total_exonerado', 'def' => '', 'req' => false],
                ['key' => 'total_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_ventas', 'def' => '', 'req' => true],
                ['key' => 'total_descuentos', 'def' => '', 'req' => false],
                ['key' => 'total_ventas_neta', 'def' => '', 'req' => true],
                ['key' => 'totalDesgloseImpuesto', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos_asumidos_fabrica', 'def' => '', 'req' => false],
                ['key' => 'totalIVADevuelto', 'def' => '0', 'req' => false],
                ['key' => 'totalOtrosCargos', 'def' => '', 'req' => false],
                ['key' => 'total_comprobante', 'def' => '', 'req' => true],
                ['key' => 'otros', 'def' => '', 'req' => false],
                ['key' => 'otrosType', 'def' => '', 'req' => false],
                ['key' => 'detalles', 'def' => '', 'req' => true],
                ['key' => 'informacion_referencia', 'def' => '', 'req' => false],
                ['key' => 'otrosCargos', 'def' => '', 'req' => false],
            ],
            'file' => 'genXML.php',
        ],
        [
            'r' => 'gen_xml_fec',
            'action' => 'genXMLFec',
            'access' => 'users_openAccess',
            'access_params' => 'accessName',
            'params' => [
                ['key' => 'clave', 'def' => '', 'req' => true],
                ['key' => 'proveedor_sistemas', 'def' => '', 'req' => true],
                ['key' => 'codigo_actividad_emisor', 'def' => '', 'req' => false],
                ['key' => 'codigo_actividad_receptor', 'def' => '', 'req' => true],
                ['key' => 'consecutivo', 'def' => '', 'req' => true],
                ['key' => 'fecha_emision', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre', 'def' => '', 'req' => true],
                ['key' => 'emisor_tipo_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_num_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'emisor_provincia', 'def' => '', 'req' => true],
                ['key' => 'emisor_canton', 'def' => '', 'req' => true],
                ['key' => 'emisor_distrito', 'def' => '', 'req' => true],
                ['key' => 'emisor_barrio', 'def' => '', 'req' => false],
                ['key' => 'emisor_otras_senas', 'def' => '', 'req' => true],
                ['key' => 'emisor_otras_senas_extranjero', 'def' => '', 'req' => false],
                ['key' => 'emisor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_email', 'def' => '', 'req' => true],
                ['key' => 'receptor_nombre', 'def' => '', 'req' => true],
                ['key' => 'receptor_tipo_identif', 'def' => '', 'req' => true],
                ['key' => 'receptor_num_identif', 'def' => '', 'req' => true],
                ['key' => 'receptor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'receptor_provincia', 'def' => '', 'req' => false],
                ['key' => 'receptor_canton', 'def' => '', 'req' => false],
                ['key' => 'receptor_distrito', 'def' => '', 'req' => false],
                ['key' => 'receptor_barrio', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas', 'def' => '', 'req' => false],
                ['key' => 'receptor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_email', 'def' => '', 'req' => false],
                ['key' => 'registrofiscal8707', 'def' => '', 'req' => false],
                ['key' => 'condicion_venta', 'def' => '', 'req' => true],
                ['key' => 'condicion_venta_otros', 'def' => '', 'req' => false],
                ['key' => 'plazo_credito', 'def' => '0', 'req' => false],
                ['key' => 'medios_pago', 'def' => '', 'req' => true],
                ['key' => 'cod_moneda', 'def' => '', 'req' => true],
                ['key' => 'tipo_cambio', 'def' => '', 'req' => true],
                ['key' => 'total_serv_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exentos', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exonerados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_merc_gravada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exenta', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exonerada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_no_sujeta', 'def' => '', 'req' => false],
                ['key' => 'total_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_exento', 'def' => '', 'req' => false],
                ['key' => 'total_exonerado', 'def' => '', 'req' => false],
                ['key' => 'total_no_sujeto', 'def' => '', 'req' => false],
                ['key' => 'total_ventas', 'def' => '', 'req' => true],
                ['key' => 'total_descuentos', 'def' => '', 'req' => false],
                ['key' => 'total_ventas_neta', 'def' => '', 'req' => true],
                ['key' => 'totalDesgloseImpuesto', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos_asumidos_fabrica', 'def' => '', 'req' => false],
                ['key' => 'totalOtrosCargos', 'def' => '', 'req' => false],
                ['key' => 'total_comprobante', 'def' => '', 'req' => true],
                ['key' => 'otros', 'def' => '', 'req' => false],
                ['key' => 'otrosType', 'def' => '', 'req' => false],
                ['key' => 'detalles', 'def' => '', 'req' => true],
                ['key' => 'informacion_referencia', 'def' => '', 'req' => true],
                ['key' => 'otrosCargos', 'def' => '', 'req' => false],
            ],
            'file' => 'genXML.php',
        ],
        [
            'r' => 'gen_xml_fee',
            'action' => 'genXMLFee',
            'access' => 'users_openAccess',
            'access_params' => 'accessName',
            'params' => [
                ['key' => 'clave', 'def' => '', 'req' => true],
                ['key' => 'proveedor_sistemas', 'def' => '', 'req' => true],
                ['key' => 'codigo_actividad_emisor', 'def' => '', 'req' => true],
                ['key' => 'consecutivo', 'def' => '', 'req' => true],
                ['key' => 'fecha_emision', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre', 'def' => '', 'req' => true],
                ['key' => 'emisor_tipo_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_num_identif', 'def' => '', 'req' => true],
                ['key' => 'emisor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'emisor_provincia', 'def' => '', 'req' => true],
                ['key' => 'emisor_canton', 'def' => '', 'req' => true],
                ['key' => 'emisor_distrito', 'def' => '', 'req' => true],
                ['key' => 'emisor_barrio', 'def' => '', 'req' => false],
                ['key' => 'emisor_otras_senas', 'def' => '', 'req' => true],
                ['key' => 'emisor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_tel', 'def' => '', 'req' => false],
                ['key' => 'emisor_email', 'def' => '', 'req' => true],
                ['key' => 'receptor_nombre', 'def' => '', 'req' => false],
                ['key' => 'receptor_tipo_identif', 'def' => '', 'req' => true],
                ['key' => 'receptor_num_identif', 'def' => '', 'req' => true],
                ['key' => 'receptor_nombre_comercial', 'def' => '', 'req' => false],
                ['key' => 'receptor_otras_senas_extranjero', 'def' => '', 'req' => false],
                ['key' => 'receptor_cod_pais_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_tel', 'def' => '', 'req' => false],
                ['key' => 'receptor_email', 'def' => '', 'req' => false],
                ['key' => 'registrofiscal8707', 'def' => '', 'req' => false],
                ['key' => 'condicion_venta', 'def' => '', 'req' => true],
                ['key' => 'condicion_venta_otros', 'def' => '', 'req' => false],
                ['key' => 'plazo_credito', 'def' => '', 'req' => false],
                ['key' => 'medios_pago', 'def' => '', 'req' => false],
                ['key' => 'detalles', 'def' => '', 'req' => true],
                ['key' => 'otrosCargos', 'def' => '', 'req' => false],
                ['key' => 'cod_moneda', 'def' => '', 'req' => true],
                ['key' => 'tipo_cambio', 'def' => '', 'req' => true],
                ['key' => 'total_serv_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_serv_exentos', 'def' => '', 'req' => false],
                ['key' => 'total_merc_gravada', 'def' => '', 'req' => false],
                ['key' => 'total_merc_exenta', 'def' => '', 'req' => false],
                ['key' => 'total_gravados', 'def' => '', 'req' => false],
                ['key' => 'total_exento', 'def' => '', 'req' => false],
                ['key' => 'total_ventas', 'def' => '', 'req' => true],
                ['key' => 'total_descuentos', 'def' => '', 'req' => false],
                ['key' => 'total_ventas_neta', 'def' => '', 'req' => true],
                ['key' => 'totalDesgloseImpuesto', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos', 'def' => '', 'req' => false],
                ['key' => 'total_impuestos_asumidos_fabrica', 'def' => '', 'req' => false],
                ['key' => 'totalOtrosCargos', 'def' => '', 'req' => false],
                ['key' => 'total_comprobante', 'def' => '', 'req' => true],
                ['key' => 'informacion_referencia', 'def' => '', 'req' => false],
                ['key' => 'otros', 'def' => '', 'req' => false],
            ],
            'file' => 'genXML.php',
        ],
        [
            'r' => 'test',
            'action' => 'test',
            'access' => 'users_openAccess',
            'access_params' => 'accessName',
            'file' => 'genXML.php',
        ],
    ];

    return $paths;
}

/* * *********************************************** */
// In the access you can use users_openAccess if you want anyone can use the function
// or users_loggedIn if the user must be logged in
/* * *********************************************** */

/**
 * Get the perms for this module
 */
function MODULENAME_access()
{

    $perms = [
        [
            // A human readable name
            'name' => 'Do something with this module',
            // Something to remember what it is for
            'description' => 'What can be achieved with this permission',
            // Internal machine name, no spaces, no funny symbols, same rules as a variable
            // Use yourmodule_ prefix
            'code' => 'mymodule_access_one',
            // Default value in case it is not set
            'def' => false, // Or true, you decide
        ],
    ];
}

/**@}*/
/** @}*/
